version: '3'

services:
    database:
        image: 'postgres:alpine'
        environment:
            POSTGRES_PASSWORD: main
            POSTGRES_USER: main
            POSTGRES_DB: main
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/#ports for more information.
            - '5432:5432'

#    php:
#        build: ./docker/php
#        environment:
#            - APP_ENV=${APP_ENV}
#            - APP_SECRET=${APP_SECRET}
#            - DATABASE_URL="postgresql://main:main@database:5432/main?serverVersion=13&charset=utf8"
#        volumes:
#            - ./:/var/www:cached
#            - ./docker/logs/symfony/:/var/www/var/logs:cached
#        depends_on:
#            - database
#        links:
#            - database
#        networks:
#            - network
#        ports:
#            - "9000:9000"
#
#    nginx:
#        build: ./docker/nginx
#        volumes_from:
#            - php
#        volumes:
#            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
#            - ./docker/nginx/sites-available/:/etc/nginx/sites-available
#            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
#            - ./docker/logs/nginx/:/var/log/nginx:cached
#        depends_on:
#            - php
#        links:
#            - php
#        networks:
#            - network
#        ports:
#            - "80:80"
#            - "443:443"
#
#networks:
#    network:
#        driver: bridge
